version: '3.4'

services:
  integrator:
    image: ${DOCKER_REGISTRY-}integrator
    build:
      context: .
      dockerfile: Integrator\Dockerfile

  networkservice:
    image: ${DOCKER_REGISTRY-}networkservice
    build:
      context: .
      dockerfile: NetworkService\Dockerfile


  virusservices:
    image: ${DOCKER_REGISTRY-}virusservices
    build:
      context: .
      dockerfile: VirusServices\Dockerfile


  locationservice:
    image: ${DOCKER_REGISTRY-}locationservice
    build:
      context: .
      dockerfile: LocationService\Dockerfile

